### ISSUE TITLE
Migrate to Gogo v1.0.0?

### ISSUE THREAD

**Issue by cnoelle** [ctron/net.luminis.cmc#1]
Hi, any plans to migrate this project to the current Gogo version? 

The preferred option would be to support both versions < 1.0.0 and >= 1.0.0 at the same time, I guess, but I have no clue how this can be achieved. The fork at https://github.com/cnoelle/net.luminis.cmc works fine with the new version, but not the old one... the commands are available, but parameters and descriptors do not work as expected (because the package import _org.apache.felix.service.command_ fails).

**Comment by ctron** [comment]
Currently I am not working on anything like that. However I would be happy to help you merge your changes into this repository.

However I am not sure I understand what you are doing. To me it looks like you simply changed the dependency to a newer version. However you are not using any newer APIs. So in theory you should be able to drop in the existing version into an environment using Gogo 1.x, as not maven but OSGi dependencies are the important ones.

**Comment by cnoelle** [comment]
The API is unchanged indeed, and the project can be built against both versions. But there is an issue with the package import _org.apache.felix.service.command_: the old version of gogo runtime exports the package with status=provisional attribute, which is gone in the new one... furthermore, the old version forces all bundles trying to import the package to set a filter on this attribute, using a 'mandatory=status' directive. This implies that you cannot declare an import statement matching both versions, and the bundle will only resolve against the version it was built against. Quite annoying feature, I think... my workaround is to make the package import optional, because the commands still work without the annotations package. The drawback is that optional parameters become mandatory, and the syntax changes slightly, if running with Gogo < v1: e.g., instead of `cm:list (-s)` you will need to type `cm:list true/false`. 

On the other hand, it is probably time to migrate to the current Gogo version anyway, so if you are fine with the changes I can send you a pull request.

By the way, the rationale for the status attribute is explained here: http://felix.apache.org/documentation/development/provisional-osgi-api-policy.html
and the attributes matching:
https://osgi.org/specification/osgi.core/7.0.0/framework.module.html#i2480178

**Comment by ctron** [comment]
The main reason for me to build this was to use this with Eclipse Kura, which seems to be still stuck with Gogo 0.10.0 … Although Eclipse Photon ships with 1.0.x … 

~~~
44	ACTIVE      org.apache.felix.gogo.command_1.0.2.v20170914-1324
45	ACTIVE      org.apache.felix.gogo.runtime_1.0.6.v20170914-1324
46	ACTIVE      org.apache.felix.gogo.shell_1.0.0.v20170914-1324
~~~

So could we can settle for 1.0.x …

**Comment by cnoelle** [comment]
Thanks for merging :+1:  
Would you mind deploying the new version to Maven central as well?

**Comment by ctron** [comment]
Yes, I will do that.

**Comment by ctron** [comment]
Done.
